name: Create txt file of repos with GitHub Pages for a specific user
on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'sitemap.txt'
  schedule:
  - cron: "15,30,45 * * * *"
jobs:
  create-txt-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get list of repos with GitHub Pages for a specific user
      run: |
        REPOS=$(curl https://api.github.com/users/ScorchChamp/repos?per_page=100)
        echo $REPOS | jq -r '.[] | select(try .has_pages==true) | "https://scorchchamp.github.io/" + .name' > sitemap.txt  
    - name: Print the result sitemap
      run: cat sitemap.txt
    - name: Upload Sitemap
      uses: actions/upload-artifact@v2
      with:
        name: sitemap
        path: sitemap.txt
    - name: Commit and push the artifact
      uses: actions/git@v2
      with:
        repo: ${{github.repository}}
        branch: main
        message: Add sitemap.txt to my-artifact-branch
        actions: push
