name: Create txt file of repos with GitHub Pages for a specific user
on: 
  push:
    branches:
      - main
  schedule:
  - cron: "15,30,45 * * * *"
jobs:
  create-txt-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get list of repos with GitHub Pages for a specific user
      run: |
        USERNAME=ScorchChamp
        REPOS=$(curl https://api.github.com/users/$USERNAME/repos?q=github-pages+in:topics)
        echo $REPOS > repos.txt
    - name: Upload txt file to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: repos-with-github-pages-scorchchamp.txt
        path: sitemap.txt
