name: Create txt file of repos with GitHub Pages for a specific user
on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'sitemap.txt'
  schedule:
  - cron: "15,30,45 * * * *"
jobs:
  create-txt-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Get list of repos with GitHub Pages for a specific user
      run: |
        REPOS=$(curl https://api.github.com/users/ScorchChamp/repos?per_page=100)
        echo $REPOS | jq -r '.[] | select(try .has_pages==true) | "https://scorchchamp.github.io/" + .name' > sitemap.txt  
    - name: Print the result sitemap
      run: cat sitemap.txt
    - name: Upload Sitemap
      uses: actions/upload-artifact@v3
      with:
        name: sitemap
        path: sitemap.txt
    - name: GIT Commit Build Artifacts
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "username@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
