name: Create txt file of repos with GitHub Pages for a specific user
on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'sitemap.txt'
  schedule:
  - cron: "0 0 * * *"
jobs:
  create-txt-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Get list of repos with GitHub Pages for a specific user
      run: |
        REPOS=$(curl https://api.github.com/users/ScorchChamp/repos?per_page=100)
        echo $REPOS | jq -r '.[] | select(try .has_pages==true) | "https://scorchchamp.github.io/" + .name' > sitemap.txt  
    - name: Print the result sitemap
      run: cat sitemap.txt
    - name: Upload Sitemap
      uses: actions/upload-artifact@v3
      with:
        name: sitemap
        path: sitemap.txt
    - name: run step if REPOS is empty
      if: ${{!contains(env.REPOS, 'https')}}
      run: exit 0
    - name: Commit and push the artifact
      continue-on-error: true
      run: |
          git config --local user.email "39032749+ScorchChamp@users.noreply.github.com" &&\
          git config --local user.name "ScorchChamp" &&\
          git add sitemap.txt &&\
          git commit -m "Add sitemap.txt" &&\
          git push
