name: Create txt file of repos with GitHub Pages for a specific user
on: 
  push:
    branches:
      - main
  schedule:
  - cron: "15,30,45 * * * *"
jobs:
  create-txt-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get list of repos with GitHub Pages for a specific user
      run: |
        REPOS=$(curl https://api.github.com/users/ScorchChamp/repos?per_page=100)
        echo $(echo $REPOS | jq -r '.[] | select(try .has_pages==true) | .name | map("https://scorchchamp.github.io/" + .)') > sitemap.txt
    - name: Upload txt file to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: repos-with-github-pages-scorchchamp.txt
        path: sitemap.txt
